apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: m300-backend:v2
        ports:
        - containerPort: 5000
        env:
        - name: FOOTBALL_API_KEY
          valueFrom:
            secretKeyRef:
              name: football-api-secret
              key: api-key
