name: Deploy Fussball Dashboard

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.Fussball_dashboard }}
          script: |
            cd ~/M300
            git pull origin main
            docker compose down
            docker compose build
            docker compose up -d
